base_color:
  - 228
  - 100
  - 100
highlight_points_color_1:
  - 180
  - 87
  - 200
highlight_points_color_2:
  - 228
  - 140
  - 140

period_time: 1000 * 2 
times: 2
frame_num: 24
wait: 60 
seed_points_num: 2000 
highlight_rate: 0.2
frame_width: 1024 
frame_height: 980 
scale: 10
title: "I Love You"
background_img_dir: "imgs"
set_bg_imgs: False 
bg_weight: 0.4
curve_weight: 1
